---
### PersistentVolume  ###
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes: [ReadWriteMany]
  hostPath:
    # TODO: You can probably just change `/npayne81/work` to wherever you cloned this repo
    path: /Users/npayne81/work/airflow-sandbox/airflow-helm/example-dags
  persistentVolumeReclaimPolicy: Retain
---
### PersistentVolumeClaim  ###
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pvc
  namespace: airflow
spec:
  storageClassName: hostpath
  volumeName: airflow-dags
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 1Gi
