---
config:
  webserver:
    expose_config: 'True'
webserverSecretKey: af67ea96c649d2448f86e6f0893e4f1f
# executor: "CeleryExecutor"
executor: KubernetesExecutor
dags:
  persistence:
    # Enable persistent volume for storing dags
    enabled: true
    ## the name of an existing PVC to use (see airflow-volume.yml)
    existingClaim: airflow-dags-pvc
    ## optional subpath for dag volume mount
    subPath:
image:
  repository: avant.jfrog.io/shared-images/avant-airflow
  tag: dev
  pullPolicy: IfNotPresent
  uid: 50000
  gid: 0
dagProcessor:
  enabled: true
