---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pause-non-prod-airflow-dags
spec:
  # schedule: 0 23 * * *  # Run every day at 11 PM
  # cron schedule to run every minute
  schedule: '*/1 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: docker.io/library/local:pause-running-airflow-1-dags-k8-cron
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - python3
                - app.py
          restartPolicy: OnFailure
